//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherStation.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherStationAllView
    {
        public long Date { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string InventoryNumber { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
        public string State { get; set; }
        public string Department { get; set; }
        public string WorkProfile { get; set; }
        public long NextDate { get; set; }
        public string Suitability { get; set; }
        public decimal Cost { get; set; }
    }
}
